using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;
using System.Text;

namespace Dynamic.Script_8D5A38C5A7BD837
{
	// Script generated by Pega Robotics Studio 8.0.1087.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8D5A38C5A7BD837")]
	public sealed class Script
	{
		public String DataTableToXML(DataTable dataTable, String tableName, String setName)
		{
			if(!String.IsNullOrEmpty(tableName))
			{
				dataTable.TableName = tableName;
			}
			if(!String.IsNullOrEmpty(setName))
			{
				dataTable.DataSet.DataSetName = setName;
			}
			using (var stream = new MemoryStream())
			{
				dataTable.WriteXml(stream);
				return Encoding.UTF8.GetString(stream.GetBuffer(), 0, (int) stream.Length);
			}
		}
	}
}
