using System;
using System.Collections;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;
using System.Data;

namespace Dynamic.Script_8D589F9AFF05B20
{
	// Script generated by Pega Robotics Studio 8.0.1063.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8D589F9AFF05B20")]
	public sealed class Script
	{
		public String BankLocationStringToXML(String input)
		{
			input = input.Trim();
			String[] rows = input.Split(new[] {"!/!"}, StringSplitOptions.RemoveEmptyEntries);
			String xml = "<BankLocations>";
			foreach(var _row in rows) 
			{
				var row = _row.Trim();
				if(row.Length > 0) 
				{
					try
					{
						xml += "<BankLocation>";
						String[] elems = row.Split(new[] {"~/~"}, StringSplitOptions.RemoveEmptyEntries);
						xml += "<BankID>BOFA</BankID>";
						xml += "<Title>" + elems[0] + "</Title>";
						xml += "<Address>" + elems[1] + "</Address>";
						xml += "<CurrentStatus>" + elems[2] + "</CurrentStatus>";
						xml += "</BankLocation>";
					} catch(Exception ex) 
					{
						
					}
				}
			}
			xml += "</BankLocations>";
			return xml;
		}

		public String BankLocationXMLFromLookupTable(DataTable dataTable)
		{
			String xml = "<BankLocations>";
			foreach(DataRow row in dataTable.Rows)
			{ 
				string title = row["Title"].ToString();
				string address = row["Address"].ToString();
				string isOpen = row["IsOpen"].ToString();

				xml += "<BankLocation>";
				xml += "<BankID>BOFA</BankID>";
				xml += "<Title>" + title + "</Title>";
				xml += "<Address>" + address + "</Address>";
				xml += "<CurrentStatus>" + isOpen + "</CurrentStatus>";
				xml += "</BankLocation>";
			}
			xml += "</BankLocations>";
			return xml;
		}
	}
}
